version: '3.9'
services:
  front:
    build:
      context: .
    ports:
    - '5173:5173'
    volumes:
    - .:/websocket-frontend
    command: bash start.sh
    stdin_open: true
    #environment:
    networks:
      - websocket-net

networks:
  websocket-net:
    name: websocket-net
    external: true